@startuml
'https://plantuml.com/class-diagram

class sum
class Number1
class Number2
class Number3
class Number4
class Number5

sum <|-- Number1
sum <|-- Number2
sum <|-- Number3
sum <|-- Number4
sum <|-- Number5


@enduml